### ISSUE TITLE
Convert Post 1.0.1 Tags to Proper Releases

### ISSUE THREAD

**Issue by mliberatore** [irace/ObjectiveCHTMLParser#8]
Could [the tags](https://github.com/irace/BRYHTMLParser/tags) be made into proper releases? Currently, the ["Releases" tab in Github](https://github.com/irace/BRYHTMLParser/releases) shows `1.0.1` as the latest release, which can be misleading.

![screen shot 2015-11-02 at 9 15 58 am](https://cloud.githubusercontent.com/assets/7883805/10885961/f1d46e10-814d-11e5-8aff-801a1f716f18.png)

**Comment by paulbruneau** [comment]
How about just a new 2.1.3 release? Will that suffice, @mliberatore ?

**Comment by mliberatore** [comment]
Yes, @paulbruneau, thanks.
