### ISSUE TITLE
HTMLNode protocol declaration missing in HTMLParser.h

### ISSUE THREAD

**Issue by Khronoss** [irace/ObjectiveCHTMLParser#9]
With cocoapods v1.0 and Xcode 7.3, I get and error when building my project saying that in the HTMLParser.h file, there is no "type or protocol named HTMLNode".

I fixed it by adding the #import "HTMLNode.h" in the HTMLParser.h file, because that's where the protocol is declared, and it fixed my problem.

**Comment by irace** [comment]
A pull request would be great.

**Comment by techinpark2** [comment]
same problem..

**Comment by irace** [comment]
Same answer...

> A pull request would be great.

**Comment by paulbruneau** [comment]
Looks like the issue was solved with https://github.com/irace/BRYHTMLParser/pull/10
